name: test

on: [push, pull_request]

jobs:
    test:
        name: ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                node-version: [12]
                os: [ubuntu-latest, windows-latest, macOS-latest]
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
            - uses: microsoft/playwright-github-action@v1
            - run: npm i -g yarn@1
            - run: yarn
            - run: yarn test
